version: '3'
services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      FORGEVERSION: "14.23.5.2808"
      MEMORY: "2G"
    volumes:
      - /opt/minecraft:/data

    tty: true
    stdin_open: true
    restart: always

